### ISSUE TITLE
Don't count spiders as 1 minion

### ISSUE THREAD

**Issue by exp111** [JavidPack/SummonersAssociation#6]
The [spider staff](https://terraria.gamepedia.com/Spider_Staff) spawns minions that count as 0.75 minion. Thus allowing you to spawn 4 minions while only having 3 slots. 
Any chance to use this in the minion history book instead of "full" minions?

**Comment by direwolf420** [comment]
the book counts the "number of weapon usages" instead of "number of minion slots summoned per use", same thing happens with the optic staff

**Comment by direwolf420** [comment]
This will be fixed for the next update in a few days
